[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbmodem1101
monitor_port = /dev/cu.usbmodem1101
lib_deps =
    https://github.com/sparkfun/SparkFun_MAX3010x_Sensor_Library.git
